os: Windows Server 2012 R2

branches:
  only:
    - master

skip_tags: true

clone_folder: c:\gopath\src\github.com\grooveid\wincrypto

environment:
  GOPATH: c:\gopath
  matrix:
  - GOARCH: amd64
    GOVERSION: 1.9
    GOROOT: c:\go
    DOWNLOADPLATFORM: "x64"

install:
  - go version
  - go env
  - go get -u golang.org/x/tools/cmd/cover

build_script:
  - cd c:\gopath\src\github.com\grooveid\wincrypto
  - go get -v -t ./...
  - go build
  - go test -v -cover ./...

# disable automatic tests
test: off

# disable deployment
deploy: off